=== SnehitaAmara/Ep-practical/Task2.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT students_info (student+)>
<!ELEMENT student (id,reg_no,name,avg,dob,time,mobile,distinction)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT reg_no (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT avg (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT distinction (#PCDATA)>

=== SnehitaAmara/Ep-practical/task2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE students_info SYSTEM "Task2.dtd">

<students_info>
	<student>
		<id> 1 </id>
		<reg_no> 123 </reg_no>
		<name> Snehita </name>
		<avg> 88 </avg>
		<dob> 19/10/01 </dob>
		<time> 10:12 </time>
		<mobile> 9911220096 </mobile>
		<distinction> YES </distinction>
	</student>

	<student>
		<id> 2 </id>
		<reg_no> 135 </reg_no>
		<name> Priya </name>
		<avg> 89 </avg>
		<dob> 12/12/01 </dob>
		<time> 10:00 </time>
		<mobile> 9900221167 </mobile>
		<distinction> NO </distinction>
	</student>

	<student>
		<id> 3 </id>
		<reg_no> 421 </reg_no>
		<name> Ramya  </name>
		<avg> 92 </avg>
		<dob> 30/03/02 </dob>
		<time> 10:10 </time>
		<mobile> 8263518904 </mobile>
		<distinction> YES </distinction>
	</student>

	<student>
		<id> 4 </id>
		<reg_no> 310 </reg_no>
		<name> Deepika  </name>
		<avg> 77 </avg>
		<dob> 23/06/03 </dob>
		<time> 9:30 </time>
		<mobile> 7109375139 </mobile>
		<distinction> NO </distinction>
	</student>

	<student>
		<id> 5 </id>
		<reg_no> 583 </reg_no>
		<name> Mary  </name>
		<avg> 85 </avg>
		<dob> 15/11/04 </dob>
		<time> 12:00 </time>
		<mobile> 9182736451 </mobile>
		<distinction> YES </distinction>
	</student>

</students_info>
